### ISSUE TITLE
First bookmark not always on top row.

### ISSUE THREAD

**Issue by ageras1** [darauble/bookmark_manager#1]
If you are going to develop this further, i noticed that usually from left to right the first bookmark goes to the second row and the next one to the first row, some times it is unavoidable with many bookmarks close together but i think (as much i can understand the code) you check if the first one collides with the next one on the right you send it to the next row.(?) Maybe check only if a bookmark collides to the left and move it to the next row if it does and move on to the next bookmark, check the left....

Thanks for the plugin it makes great difference for me.

I just put this together (I am not a programmer)
![sdrpp](https://user-images.githubusercontent.com/88296235/176415369-6d2463c3-c22d-4dee-928a-baf8e5445d18.png)

**Comment by darauble** [comment]
The actual "issue" is that bookmarks are read from storage file unsorted and added by their frequency. So if the first bookmark by frequency is a bit more to the right, and the next a bit to left, we get the first row populated "earlier".

I'll try to add sorting of bookmarks by frequency and that might actually solve their alignment left-to-right in a more "intuitive" manner.

Regarding collisions the bookmarks are checked on both sides and additionally if one (e.g. with shorter name) falls fully into another bookmark. Also, if you inspect the code closer, you'll see that I actually search for _minimum_ collision. Why? Because when there are many bookmarks, finding an empty space finally might become impossible, so the minimum overlap is best bet.

Unfortunately, I am going off for a long holiday and be back only in August to do further development. I'll see if I can cram the bookmark sorting during next day(s).

Linkėjimai.

**Comment by darauble** [comment]
Please see if sorted bookmarks make it more pleasant to the eye.

Linkėjimai.

**Comment by ageras1** [comment]
Yes sorted bookmarks does the trick, just tried it.

I noticed the minimum collision, it work perfect on some long bookmarks that i have.

Thanks again and have great holidays.

**Comment by darauble** [comment]
IIRC, Gqrx saves all bookmarks in one heap and they are distinguished by tags. In SDR++ bookmarks are saved in separate lists. Even if lists are sorted by frequency, the displayed bookmarks would need re-sorting anyway, as lists might have them intermingled. So from my humble perspective there's no point of saving them sorted. Also, sorting is an infrequent operation (startup, bookmark editing), so it does not cost much.

Linkėjimai.
