### ISSUE TITLE
What about Windows?

### ISSUE THREAD

**Issue by kmp56** [darauble/bookmark_manager#2]
Works SUPER with my Ubuntu 22.04. But what about Windows? Can you provide a suitable .dll file for Win10 / 11_x64 working with SDR++ v1.1.0?

**Comment by betzburger** [comment]
Just wanted to mention that the bookmark_manager does a brilliant job on my Mac M1. A Windows version for my second machine would be nice (but I have no idea how to do it for Windows by myself).

**Comment by kmp56** [comment]
I can compile a Linux version of SDR ++ myself with Bookmark_manager and Radiosonde plugins and I don't have to wait for the final binaries but Windows compilations are not for me, unfortunately ...

**Comment by darauble** [comment]
Hi guys. I am sorry, I am full linuxoid myself. Last time I compiled something for Windows in my studies, which were more than 20 years ago.

Nevertheless, if you can compile SDR++ with Linux or Mac, please read the SDR++ compilation guide, there are really detailed Windows instructions.

Also, as there's demand (albeit faint), I can try it, however I don't have a date to promise. If one of you is first to do it, let me know how it goes. 

All that said I also didn't have a plan to provide binaries.

**Comment by betzburger** [comment]
Well, yeeeeeeaaaaah. 
Tried this Windows thing and completely failed :-)  
Installed the Visual Studio, installed Git.  Installed other necessary stuff but when I try to compile or install some of the dependencies that are needed I get errors for other things that are missing and I have no idea how to fix this because I have zero experience with Windows compilers.
Guess I stick with my macOS version then. Windows version would be nice, sure, but so what.

**Comment by kmp56** [comment]
It's a pity, maybe there will be someone who can, we'll wait ...
@darauble - Thanks again for a great plugin !

**Comment by darauble** [comment]
Come on... it could not be _that hard_. :-D Please go to release part, there's an alpha build of DLL. Note: I built it on Windows 11 with Visual Studio _MSBuild version 17.3.1+2badb37d1 for .NET Framework_. I don't know anything about Windows dependencies, so DLL might not load. Please try it out, but I am afraid I might _not_ be able to help on troubleshooting...

**Comment by betzburger** [comment]
How can you do this in such a short time? 
This thing works! 
In my case I use Windows 10. 
WORKS! 
I feel small and stupid in comparison...

**Comment by darauble** [comment]
Dear @betzburger, could you possibly share a _.so_ that you've built for Mac? I don't have a Mac around, so the prebuilt binary might be useful for other Mac users. I would publish it in the Releases with a honorary mention of the builder :-)

**Comment by betzburger** [comment]
Hi darauble, 
in my case it is not a .so file but a .dylib file. 
It is for the new generation of Mac computers that have an Apple Silicon (based on ARM technology) processor.
Unfortunately, the SDR++ author has not yet a prebuilt Apple Silicon version ready to download, only for the older Intel lineup. So we are a bit ahead of time :-)

OK, let's assume you HAVE the Apple Silicon version of SDR++ installed.
It is configured in your users home directory (and it is a hidden directory) located at /Users/yourusername/.config/sdrpp/config.json 

In this config.json you can define the location of your modules directory.
In my case it looks like this:

```
    "modulesDirectory": "/usr/local/lib/sdrpp/plugins",
    "offset": 0.0,
    "offsetMode": 0,
    "resourcesDirectory": "/usr/local/share/sdrpp",
```


You have to copy the **bookmark_manager.dylib** file into the modules directory.

In the same config.json file you then enable the bookmark_manager.
Just add this code under "moduleInstances"

Looks like this:

```
    "moduleInstances": {
        "Bookmark Manager": {
            "enabled": true,
            "module": "bookmark_manager"
        },
```

Because macOS is a UNIX system, it is not that far away from Linux.

Have fun!

[bookmark_manager.dylib.zip](https://github.com/darauble/bookmark_manager/files/9563221/bookmark_manager.dylib.zip)

**Comment by darauble** [comment]
Thank you!

**Comment by betzburger** [comment]
Hm. I wanted to post instructions on how to build SDR++ on an M1 Mac. But seems the Author of SDR++ does not like to have the program "installed" on macOS because he said it may break things when someone tries to uninstall it. Users should create or use a pre-built .app bundle file. He may be right.
Anyhow, if you have "installed" it on your system, the files are in /usr/local/bin, usr/local/share, /usr/local/lib.

**Comment by kmp56** [comment]
Again, can you provide a suitable .dll file  with text-only option for Win10 / 11_x64 working with SDR++ v1.1.0 ?
We would appreciate.

**Comment by darauble** [comment]
Here you go, sir.

**Comment by betzburger** [comment]
Very cool. Thanks for the update. This bookmark manager is so much better.
I compiled an updated version of the bookmark_manager.dylib that can be used for the Apple Silicon SDR++ version.
[bookmark_manager.dylib.zip](https://github.com/darauble/bookmark_manager/files/10471856/bookmark_manager.dylib.zip)

**Comment by kmp56** [comment]
> Here you go, sir.

Thank You very much !
